packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - '@shopify/react-native-skia'
  - unrs-resolver

overrides:
  lightningcss: 1.30.2
