// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: account.sql

package repository

import (
	"context"
	"time"

	"github.com/Fantasy-Programming/nuts/server/internal/repository/dto"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type BatchCreateAccountParams struct {
	CreatedBy         *uuid.UUID          `json:"created_by"`
	Name              string              `json:"name"`
	Type              interface{}         `json:"type"`
	Subtype           *string             `json:"subtype"`
	Balance           decimal.NullDecimal `json:"balance"`
	Currency          string              `json:"currency"`
	Meta              dto.AccountMeta     `json:"meta"`
	ConnectionID      *uuid.UUID          `json:"connection_id"`
	IsExternal        *bool               `json:"is_external"`
	ProviderAccountID *string             `json:"provider_account_id"`
	ProviderName      *string             `json:"provider_name"`
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    created_by,
    name,
    type,
    subtype,
    balance,
    currency,
    meta,
    connection_id,
    is_external,
    provider_account_id,
    provider_name
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, type, balance, currency, meta, created_by, updated_by, created_at, updated_at, deleted_at, is_external, provider_account_id, provider_name, sync_status, last_synced_at, connection_id, subtype, shared_finance_id
`

type CreateAccountParams struct {
	CreatedBy         *uuid.UUID          `json:"created_by"`
	Name              string              `json:"name"`
	Type              interface{}         `json:"type"`
	Subtype           *string             `json:"subtype"`
	Balance           decimal.NullDecimal `json:"balance"`
	Currency          string              `json:"currency"`
	Meta              dto.AccountMeta     `json:"meta"`
	ConnectionID      *uuid.UUID          `json:"connection_id"`
	IsExternal        *bool               `json:"is_external"`
	ProviderAccountID *string             `json:"provider_account_id"`
	ProviderName      *string             `json:"provider_name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.CreatedBy,
		arg.Name,
		arg.Type,
		arg.Subtype,
		arg.Balance,
		arg.Currency,
		arg.Meta,
		arg.ConnectionID,
		arg.IsExternal,
		arg.ProviderAccountID,
		arg.ProviderName,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Meta,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsExternal,
		&i.ProviderAccountID,
		&i.ProviderName,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.ConnectionID,
		&i.Subtype,
		&i.SharedFinanceID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
UPDATE accounts
SET
    deleted_at = current_timestamp
WHERE id = $1
RETURNING id, name, type, balance, currency, meta, created_by, updated_by, created_at, updated_at, deleted_at, is_external, provider_account_id, provider_name, sync_status, last_synced_at, connection_id, subtype, shared_finance_id
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountBalanceTimeline = `-- name: GetAccountBalanceTimeline :many
WITH
period AS (
    SELECT
        date_trunc('month', now()) - INTERVAL '11 months' AS start_month,
        date_trunc('month', now()) AS end_month
),
user_base_currency AS (
    SELECT COALESCE((SELECT currency FROM preferences WHERE user_id = $2 LIMIT 1), 'USD') AS base_currency
),
transactions_converted AS (
    SELECT
        m.account_id,
        m.transaction_datetime,
        (m.amount * COALESCE(er.rate, 1.0))::DECIMAL AS converted_amount
    FROM (
        SELECT t.account_id, t.transaction_datetime, t.amount, t.transaction_currency FROM transactions t
        WHERE t.created_by = $2 AND t.deleted_at IS NULL AND t.type IN ('income', 'expense') AND t.account_id = $1
        UNION ALL
        SELECT t.account_id, t.transaction_datetime, -t.amount, t.transaction_currency FROM transactions t
        WHERE t.created_by = $2 AND t.deleted_at IS NULL AND t.type = 'transfer' AND t.account_id = $1
        UNION ALL
        SELECT t.destination_account_id, t.transaction_datetime, t.amount, t.transaction_currency FROM transactions t
        WHERE t.created_by = $2 AND t.deleted_at IS NULL AND t.type = 'transfer' AND t.destination_account_id = $1
    ) m
    LEFT JOIN LATERAL (
        SELECT rate FROM exchange_rates er
        WHERE er.from_currency = m.transaction_currency AND er.to_currency = (SELECT base_currency FROM user_base_currency)
          AND er.effective_date <= m.transaction_datetime::DATE
        ORDER BY er.effective_date DESC
        LIMIT 1
    ) er ON TRUE
),
daily_deltas AS (
    SELECT
        date_trunc('day', transaction_datetime)::DATE AS date,
        SUM(converted_amount) AS delta
    FROM transactions_converted
    GROUP BY date_trunc('day', transaction_datetime)
),
account_anchor_balance AS (
    SELECT
        a.id AS account_id,
        a.type,
        CASE
            WHEN a.is_external THEN (a.balance * COALESCE(er.rate, 1.0))::DECIMAL
            ELSE COALESCE((SELECT SUM(tc.converted_amount) FROM transactions_converted tc), 0)
        END AS anchor_balance,
        CASE
            WHEN a.is_external THEN a.updated_at
            ELSE NOW()
        END AS anchor_date
    FROM accounts a
    LEFT JOIN LATERAL (
        SELECT rate FROM exchange_rates er
        WHERE er.from_currency = a.currency AND er.to_currency = (SELECT base_currency FROM user_base_currency)
          AND er.effective_date <= a.updated_at::DATE
        ORDER BY er.effective_date DESC
        LIMIT 1
    ) er ON TRUE
    WHERE a.id = $1 AND a.created_by = $2 AND a.deleted_at IS NULL
),
balance_timeseries AS (
    SELECT
        d.date,
        a.type,
        (
            a.anchor_balance -
            COALESCE((
                SELECT SUM(delta) FROM daily_deltas dd
                WHERE dd.date > (SELECT end_month FROM period)::DATE + interval '1 month' - interval '1 day'
                  AND dd.date <= a.anchor_date::DATE
            ), 0)
        )
        -
        COALESCE((
            SELECT SUM(delta) FROM daily_deltas dd
            WHERE dd.date > d.date
              AND dd.date <= (SELECT end_month FROM period)::DATE + interval '1 month' - interval '1 day'
        ), 0) AS daily_balance
    FROM
        generate_series(
            (SELECT start_month FROM period)::DATE,
            (SELECT end_month FROM period)::DATE + interval '1 month' - interval '1 day',
            '1 day'::interval
        ) AS d(date)
    CROSS JOIN account_anchor_balance a
),
monthly_balances AS (
    SELECT DISTINCT ON (date_trunc('month', date))
        date_trunc('month', date)::TIMESTAMPTZ AS month,
        daily_balance,
        type
    FROM balance_timeseries
    ORDER BY date_trunc('month', date), date DESC
)
SELECT
    mb.month,
    (CASE WHEN mb.type IN ('credit', 'loan') THEN mb.daily_balance * -1 ELSE mb.daily_balance END)::DECIMAL AS balance
FROM monthly_balances mb
ORDER BY mb.month
`

type GetAccountBalanceTimelineParams struct {
	AccountID uuid.UUID `json:"account_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetAccountBalanceTimelineRow struct {
	Month   time.Time      `json:"month"`
	Balance pgtype.Numeric `json:"balance"`
}

// =================================================================
// Step 1: Define the reporting period and the user's base currency
// =================================================================
// =================================================================
// Step 2: Unify and convert all transaction "movements" for the SPECIFIC account.
// =================================================================
// =================================================================
// Step 3: Pre-calculate daily net changes for the specific account.
// =================================================================
// =================================================================
// Step 4: Get the authoritative "anchor" balance for the specific account.
// =================================================================
// =================================================================
// Step 5: Generate the daily balance timeseries for the account.
// =================================================================
// =================================================================
// Final Step: Select the balance from the LAST DAY of each month.
// =================================================================
func (q *Queries) GetAccountBalanceTimeline(ctx context.Context, arg GetAccountBalanceTimelineParams) ([]GetAccountBalanceTimelineRow, error) {
	rows, err := q.db.Query(ctx, getAccountBalanceTimeline, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountBalanceTimelineRow{}
	for rows.Next() {
		var i GetAccountBalanceTimelineRow
		if err := rows.Scan(&i.Month, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountById = `-- name: GetAccountById :one
SELECT
    id,
    name,
    type,
    subtype,
    balance,
    currency,
    meta,
    is_external,
    last_synced_at,
    created_by,
    updated_at,
    connection_id
FROM accounts
WHERE
    id = $1
    AND deleted_at IS NULL
LIMIT 1
`

type GetAccountByIdRow struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Type         ACCOUNTTYPE     `json:"type"`
	Subtype      *string         `json:"subtype"`
	Balance      pgtype.Numeric  `json:"balance"`
	Currency     string          `json:"currency"`
	Meta         dto.AccountMeta `json:"meta"`
	IsExternal   *bool           `json:"is_external"`
	LastSyncedAt *time.Time      `json:"last_synced_at"`
	CreatedBy    *uuid.UUID      `json:"created_by"`
	UpdatedAt    time.Time       `json:"updated_at"`
	ConnectionID *uuid.UUID      `json:"connection_id"`
}

func (q *Queries) GetAccountById(ctx context.Context, id uuid.UUID) (GetAccountByIdRow, error) {
	row := q.db.QueryRow(ctx, getAccountById, id)
	var i GetAccountByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Subtype,
		&i.Balance,
		&i.Currency,
		&i.Meta,
		&i.IsExternal,
		&i.LastSyncedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.ConnectionID,
	)
	return i, err
}

const getAccountByProviderAccountID = `-- name: GetAccountByProviderAccountID :one

SELECT
    id,
    name,
    type,
    subtype,
    balance,
    currency,
    meta,
    created_by,
    updated_at,
    connection_id,
    provider_name,
    provider_account_id
FROM accounts
WHERE
    provider_account_id = $1
    AND created_by = $2 -- user_id
    AND deleted_at IS NULL
LIMIT 1
`

type GetAccountByProviderAccountIDParams struct {
	ProviderAccountID *string    `json:"provider_account_id"`
	CreatedBy         *uuid.UUID `json:"created_by"`
}

type GetAccountByProviderAccountIDRow struct {
	ID                uuid.UUID       `json:"id"`
	Name              string          `json:"name"`
	Type              ACCOUNTTYPE     `json:"type"`
	Subtype           *string         `json:"subtype"`
	Balance           pgtype.Numeric  `json:"balance"`
	Currency          string          `json:"currency"`
	Meta              dto.AccountMeta `json:"meta"`
	CreatedBy         *uuid.UUID      `json:"created_by"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ConnectionID      *uuid.UUID      `json:"connection_id"`
	ProviderName      *string         `json:"provider_name"`
	ProviderAccountID *string         `json:"provider_account_id"`
}

// Or other desired order
func (q *Queries) GetAccountByProviderAccountID(ctx context.Context, arg GetAccountByProviderAccountIDParams) (GetAccountByProviderAccountIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByProviderAccountID, arg.ProviderAccountID, arg.CreatedBy)
	var i GetAccountByProviderAccountIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Subtype,
		&i.Balance,
		&i.Currency,
		&i.Meta,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.ConnectionID,
		&i.ProviderName,
		&i.ProviderAccountID,
	)
	return i, err
}

const getAccounts = `-- name: GetAccounts :many
SELECT
    id,
    name,
    type,
    subtype,
    balance,
    currency,
    is_external,
    last_synced_at,
    meta,
    updated_at,
    connection_id
FROM accounts
WHERE
    created_by = $1
    AND deleted_at IS NULL
`

type GetAccountsRow struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Type         ACCOUNTTYPE     `json:"type"`
	Subtype      *string         `json:"subtype"`
	Balance      pgtype.Numeric  `json:"balance"`
	Currency     string          `json:"currency"`
	IsExternal   *bool           `json:"is_external"`
	LastSyncedAt *time.Time      `json:"last_synced_at"`
	Meta         dto.AccountMeta `json:"meta"`
	UpdatedAt    time.Time       `json:"updated_at"`
	ConnectionID *uuid.UUID      `json:"connection_id"`
}

func (q *Queries) GetAccounts(ctx context.Context, userID *uuid.UUID) ([]GetAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsRow{}
	for rows.Next() {
		var i GetAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Subtype,
			&i.Balance,
			&i.Currency,
			&i.IsExternal,
			&i.LastSyncedAt,
			&i.Meta,
			&i.UpdatedAt,
			&i.ConnectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsBalanceTimeline = `-- name: GetAccountsBalanceTimeline :many
WITH
period AS (
    SELECT
        date_trunc('month', now()) - INTERVAL '11 months' AS start_month,
        date_trunc('month', now()) AS end_month
),
user_base_currency AS (
    SELECT COALESCE((SELECT currency FROM preferences WHERE user_id = $1 LIMIT 1), 'USD') AS base_currency
),
transactions_converted AS (
    SELECT
        m.account_id,
        m.transaction_datetime,
        (m.amount * COALESCE(er.rate, 1.0))::DECIMAL AS converted_amount
    FROM (
        -- Income/Expense
        SELECT t.account_id, t.transaction_datetime, t.amount, t.transaction_currency FROM transactions t
        WHERE t.created_by = $1 AND t.deleted_at IS NULL AND t.type IN ('income', 'expense')
        UNION ALL
        -- Transfers (out)
        SELECT t.account_id, t.transaction_datetime, -t.amount, t.transaction_currency FROM transactions t
        WHERE t.created_by = $1 AND t.deleted_at IS NULL AND t.type = 'transfer'
        UNION ALL
        -- Transfers (in)
        SELECT t.destination_account_id, t.transaction_datetime, t.amount, t.transaction_currency FROM transactions t
        WHERE t.created_by = $1 AND t.deleted_at IS NULL AND t.type = 'transfer' AND t.destination_account_id IS NOT NULL
    ) m
    LEFT JOIN LATERAL (
        SELECT rate FROM exchange_rates er
        WHERE er.from_currency = m.transaction_currency AND er.to_currency = (SELECT base_currency FROM user_base_currency)
          AND er.effective_date <= m.transaction_datetime::DATE
        ORDER BY er.effective_date DESC
        LIMIT 1
    ) er ON TRUE
),
daily_deltas AS (
    SELECT
        account_id,
        date_trunc('day', transaction_datetime)::DATE AS date,
        SUM(converted_amount) AS delta
    FROM transactions_converted
    GROUP BY account_id, date_trunc('day', transaction_datetime)
),
account_anchor_balance AS (
    SELECT
        a.id AS account_id,
        a.type,
        CASE
            WHEN a.is_external THEN (a.balance * COALESCE(er.rate, 1.0))::DECIMAL
            ELSE COALESCE((SELECT SUM(tc.converted_amount) FROM transactions_converted tc WHERE tc.account_id = a.id), 0)
        END AS anchor_balance,
        CASE
            WHEN a.is_external THEN a.updated_at
            ELSE NOW()
        END AS anchor_date
    FROM accounts a
    LEFT JOIN LATERAL (
        SELECT rate FROM exchange_rates er
        WHERE er.from_currency = a.currency AND er.to_currency = (SELECT base_currency FROM user_base_currency)
          AND er.effective_date <= a.updated_at::DATE
        ORDER BY er.effective_date DESC
        LIMIT 1
    ) er ON TRUE
    WHERE a.created_by = $1 AND a.deleted_at IS NULL
),
balance_timeseries AS (
    SELECT
        a.account_id,
        d.date,
        a.type,
        (
            a.anchor_balance -
            COALESCE((
                SELECT SUM(delta) FROM daily_deltas dd
                WHERE dd.account_id = a.account_id
                  AND dd.date > ((SELECT end_month FROM period)::DATE + interval '1 month' - interval '1 day')
                  AND dd.date <= a.anchor_date::DATE
            ), 0)
        )
        -
        COALESCE((
            SELECT SUM(delta) FROM daily_deltas dd
            WHERE dd.account_id = a.account_id
              AND dd.date > d.date
              AND dd.date <= ((SELECT end_month FROM period)::DATE + interval '1 month' - interval '1 day')
        ), 0) AS daily_balance
    FROM
        generate_series(
            (SELECT start_month FROM period)::DATE,
            (SELECT end_month FROM period)::DATE + interval '1 month' - interval '1 day',
            '1 day'::interval
        ) AS d(date)
    CROSS JOIN account_anchor_balance a
),
account_monthly_balances AS (
    SELECT DISTINCT ON (account_id, date_trunc('month', date))
        account_id,
        date_trunc('month', date)::TIMESTAMPTZ AS month,
        daily_balance,
        type
    FROM balance_timeseries
    ORDER BY account_id, date_trunc('month', date), date DESC
)
SELECT
    amb.month,
    SUM(CASE WHEN amb.type IN ('credit', 'loan') THEN amb.daily_balance * -1 ELSE amb.daily_balance END)::DECIMAL AS balance
FROM account_monthly_balances amb
GROUP BY amb.month
ORDER BY amb.month
`

type GetAccountsBalanceTimelineRow struct {
	Month   time.Time      `json:"month"`
	Balance pgtype.Numeric `json:"balance"`
}

// =================================================================
// Step 1: Define the reporting period and the user's base currency
// =================================================================
// =================================================================
// Step 2: Unify and convert all transaction "movements" for ALL accounts of the user.
// =================================================================
// =================================================================
// Step 3: Pre-calculate daily net changes for EACH account.
// =================================================================
// =================================================================
// Step 4: Get the authoritative "anchor" balance for EACH account.
// =================================================================
// =================================================================
// Step 5: Generate the daily balance timeseries for EACH account.
// =================================================================
// =================================================================
// Step 6: Select the balance from the LAST DAY of each month FOR EACH ACCOUNT.
// =================================================================
// =================================================================
// Final Step: Aggregate the monthly balances from all accounts.
// =================================================================
func (q *Queries) GetAccountsBalanceTimeline(ctx context.Context, userID uuid.UUID) ([]GetAccountsBalanceTimelineRow, error) {
	rows, err := q.db.Query(ctx, getAccountsBalanceTimeline, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsBalanceTimelineRow{}
	for rows.Next() {
		var i GetAccountsBalanceTimelineRow
		if err := rows.Scan(&i.Month, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsByConnectionID = `-- name: GetAccountsByConnectionID :many
SELECT
    id,
    name,
    type,
    subtype,
    balance,
    currency,
    meta,
    created_by,
    updated_at,
    connection_id,
    provider_name,
    provider_account_id
FROM accounts
WHERE
    connection_id = $1
    AND created_by = $2 -- user_id
    AND deleted_at IS NULL
`

type GetAccountsByConnectionIDParams struct {
	ConnectionID *uuid.UUID `json:"connection_id"`
	CreatedBy    *uuid.UUID `json:"created_by"`
}

type GetAccountsByConnectionIDRow struct {
	ID                uuid.UUID       `json:"id"`
	Name              string          `json:"name"`
	Type              ACCOUNTTYPE     `json:"type"`
	Subtype           *string         `json:"subtype"`
	Balance           pgtype.Numeric  `json:"balance"`
	Currency          string          `json:"currency"`
	Meta              dto.AccountMeta `json:"meta"`
	CreatedBy         *uuid.UUID      `json:"created_by"`
	UpdatedAt         time.Time       `json:"updated_at"`
	ConnectionID      *uuid.UUID      `json:"connection_id"`
	ProviderName      *string         `json:"provider_name"`
	ProviderAccountID *string         `json:"provider_account_id"`
}

func (q *Queries) GetAccountsByConnectionID(ctx context.Context, arg GetAccountsByConnectionIDParams) ([]GetAccountsByConnectionIDRow, error) {
	rows, err := q.db.Query(ctx, getAccountsByConnectionID, arg.ConnectionID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsByConnectionIDRow{}
	for rows.Next() {
		var i GetAccountsByConnectionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Subtype,
			&i.Balance,
			&i.Currency,
			&i.Meta,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.ConnectionID,
			&i.ProviderName,
			&i.ProviderAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsSince = `-- name: GetAccountsSince :many
SELECT
    id,
    name,
    type,
    subtype,
    balance,
    currency,
    is_external,
    last_synced_at,
    meta,
    created_at,
    updated_at,
    deleted_at,
    connection_id,
    provider_name,
    provider_account_id,
    created_by,
    updated_by
FROM accounts
WHERE
    created_by = $1
    AND (
        updated_at > $2
        OR (deleted_at IS NOT NULL AND deleted_at > $2)
    )
`

type GetAccountsSinceParams struct {
	UserID *uuid.UUID         `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

type GetAccountsSinceRow struct {
	ID                uuid.UUID       `json:"id"`
	Name              string          `json:"name"`
	Type              ACCOUNTTYPE     `json:"type"`
	Subtype           *string         `json:"subtype"`
	Balance           pgtype.Numeric  `json:"balance"`
	Currency          string          `json:"currency"`
	IsExternal        *bool           `json:"is_external"`
	LastSyncedAt      *time.Time      `json:"last_synced_at"`
	Meta              dto.AccountMeta `json:"meta"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         *time.Time      `json:"deleted_at"`
	ConnectionID      *uuid.UUID      `json:"connection_id"`
	ProviderName      *string         `json:"provider_name"`
	ProviderAccountID *string         `json:"provider_account_id"`
	CreatedBy         *uuid.UUID      `json:"created_by"`
	UpdatedBy         *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) GetAccountsSince(ctx context.Context, arg GetAccountsSinceParams) ([]GetAccountsSinceRow, error) {
	rows, err := q.db.Query(ctx, getAccountsSince, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsSinceRow{}
	for rows.Next() {
		var i GetAccountsSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Subtype,
			&i.Balance,
			&i.Currency,
			&i.IsExternal,
			&i.LastSyncedAt,
			&i.Meta,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ConnectionID,
			&i.ProviderName,
			&i.ProviderAccountID,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountsWithTrend = `-- name: GetAccountsWithTrend :many
WITH period AS (
    SELECT
        $1::TIMESTAMPTZ AS start_date,
        $2::TIMESTAMPTZ AS end_date
),

date_series AS (
    SELECT generate_series(
        (SELECT start_date FROM period),
        (SELECT end_date FROM period),
        '1 day'
    )::DATE AS date
),

account_info AS (
    -- Get account info, including creation date
    SELECT
        id AS account_id,
        name,
        type,
        subtype,
        currency,
        meta,
        created_by,
        created_at,
        updated_at,
        deleted_at
    FROM accounts
    WHERE accounts.created_by = $3
    -- Include accounts active at any point during the period
    AND created_at <= (SELECT end_date FROM period)
    AND (deleted_at IS NULL OR deleted_at > (SELECT start_date FROM period))
),

balance_calc AS (
    -- Calculate balance at the start and end of the period for each account
    SELECT
        ai.account_id,
        -- Balance just BEFORE start_date
        coalesce(sum(
            CASE
                WHEN t.transaction_datetime < (SELECT start_date FROM period) THEN
                    CASE
                        WHEN t.type = 'income' THEN t.amount
                        WHEN t.type = 'expense' THEN -t.amount
                        WHEN t.type = 'transfer' AND t.account_id = t.account_id THEN -t.amount
                        WHEN t.type = 'transfer' AND t.account_id = t.destination_account_id THEN t.amount
                        ELSE 0
                    END
                ELSE 0
            END
        ), 0)::DECIMAL AS start_balance,
        -- Balance AT end_date (inclusive)
        coalesce(sum(
            CASE
                WHEN t.transaction_datetime <= (SELECT end_date FROM period)
                    THEN
                        CASE
                            WHEN t.type = 'income' THEN t.amount
                            WHEN t.type = 'expense' THEN -t.amount
                            WHEN t.type = 'transfer' AND t.account_id = t.account_id THEN -t.amount
                            WHEN t.type = 'transfer' AND t.account_id = t.destination_account_id THEN t.amount
                            ELSE 0
                        END
                ELSE 0
            END
        ), 0)::DECIMAL AS end_balance
    FROM transactions t
    JOIN account_info ai ON (t.account_id = ai.account_id OR t.destination_account_id = ai.account_id)
    WHERE t.created_by = $3
      AND t.transaction_datetime <= (SELECT end_date FROM period)
      -- Filter transactions related to the accounts active in the period
    GROUP BY ai.account_id
),

account_trend AS (
    -- Calculate trend percentage based on actual start/end balances
    SELECT
        ai.account_id,
        ai.name,
        ai.type,
        ai.subtype,
        coalesce(bc.end_balance, 0) AS balance, -- Current balance is the end_balance
        ai.currency,
        ai.meta,
        ai.updated_at,
        CASE
            -- Avoid division by zero if start_balance is 0
            WHEN coalesce(bc.start_balance, 0) = 0 THEN
                CASE
                    -- If end balance is also 0, trend is 0
                    WHEN coalesce(bc.end_balance, 0) = 0 THEN 0
                    -- If start is 0 but end is positive/negative, trend is infinite (represent as 100% or specific value?)
                    -- Let's return 100% if end > start (0), -100% if end < start (0). Or null? Let's use 100/-100 for simplicity.
                    WHEN coalesce(bc.end_balance, 0) > 0 THEN 100.0
                    ELSE -100.0 -- or potentially 0 or NULL depending on desired behaviour
                END
            -- Normal trend calculation
            ELSE
                ( (coalesce(bc.end_balance, 0) - bc.start_balance) / ABS(bc.start_balance) * 100.0 )
        END::DECIMAL AS trend
    FROM account_info ai
    LEFT JOIN balance_calc bc ON ai.account_id = bc.account_id
    -- Ensure we only consider the balance if the account existed at the start date for trend calculation
    -- If created within the period, trend starts from 0.
    WHERE ai.created_at <= (SELECT end_date FROM period) -- Redundant check, but safe
      AND (ai.deleted_at IS NULL OR ai.deleted_at > (SELECT start_date FROM period)) -- Ensure not deleted before period start
),

balance_timeseries AS (
    SELECT
        ai.account_id,
        ds.date,
        sum(
            CASE
                WHEN t.type = 'income' THEN t.amount
                WHEN t.type = 'expense' THEN -t.amount
                WHEN t.type = 'transfer' AND t.account_id = ai.account_id THEN -t.amount
                WHEN t.type = 'transfer' AND t.destination_account_id = ai.account_id THEN t.amount
                ELSE 0
            END
        )::DECIMAL AS cumulative_balance
    FROM account_info ai
    CROSS JOIN date_series ds
    LEFT JOIN transactions t
        ON (t.account_id = ai.account_id OR t.destination_account_id = ai.account_id)
       AND t.transaction_datetime <= ds.date + interval '1 day' - interval '1 second'
       AND t.created_by = $3
    GROUP BY ai.account_id, ds.date
),

aggregated_series AS (
    SELECT
        account_id,
        jsonb_agg(
            jsonb_build_object(
                'date', date,
                'balance', cumulative_balance
            ) ORDER BY date
        ) AS timeseries
    FROM balance_timeseries
    GROUP BY account_id
)
SELECT
    at.account_id as id,
    at.name,
    at.type,
    at.subtype,
    at.balance::DECIMAL as balance, -- Balance at the end_date
    at.currency,
    at.meta,
    at.updated_at,
    at.trend::DECIMAL as trend,
    coalesce(agg.timeseries, '[]'::JSONB)::JSONB AS balance_timeseries
FROM account_trend at
LEFT JOIN aggregated_series agg ON at.account_id = agg.account_id
ORDER BY at.name
`

type GetAccountsWithTrendParams struct {
	Column1 time.Time  `json:"column_1"`
	Column2 time.Time  `json:"column_2"`
	UserID  *uuid.UUID `json:"user_id"`
}

type GetAccountsWithTrendRow struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	Type              ACCOUNTTYPE    `json:"type"`
	Subtype           *string        `json:"subtype"`
	Balance           pgtype.Numeric `json:"balance"`
	Currency          string         `json:"currency"`
	Meta              []byte         `json:"meta"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Trend             pgtype.Numeric `json:"trend"`
	BalanceTimeseries []byte         `json:"balance_timeseries"`
}

// Final query joining trend with last 3 transactions
func (q *Queries) GetAccountsWithTrend(ctx context.Context, arg GetAccountsWithTrendParams) ([]GetAccountsWithTrendRow, error) {
	rows, err := q.db.Query(ctx, getAccountsWithTrend, arg.Column1, arg.Column2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAccountsWithTrendRow{}
	for rows.Next() {
		var i GetAccountsWithTrendRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Subtype,
			&i.Balance,
			&i.Currency,
			&i.Meta,
			&i.UpdatedAt,
			&i.Trend,
			&i.BalanceTimeseries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET
    name = coalesce($1, name),
    type = coalesce($2, type),
    subtype = coalesce($3, subtype),
    balance = coalesce($4, balance),
    currency = coalesce($5, currency),
    meta = coalesce($6, meta),
    updated_by = $7
WHERE id = $8
RETURNING id, name, type, balance, currency, meta, created_by, updated_by, created_at, updated_at, deleted_at, is_external, provider_account_id, provider_name, sync_status, last_synced_at, connection_id, subtype, shared_finance_id
`

type UpdateAccountParams struct {
	Name      *string             `json:"name"`
	Type      interface{}         `json:"type"`
	Subtype   *string             `json:"subtype"`
	Balance   decimal.NullDecimal `json:"balance"`
	Currency  *string             `json:"currency"`
	Meta      dto.AccountMeta     `json:"meta"`
	UpdatedBy *uuid.UUID          `json:"updated_by"`
	ID        uuid.UUID           `json:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Subtype,
		arg.Balance,
		arg.Currency,
		arg.Meta,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.Currency,
		&i.Meta,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsExternal,
		&i.ProviderAccountID,
		&i.ProviderName,
		&i.SyncStatus,
		&i.LastSyncedAt,
		&i.ConnectionID,
		&i.Subtype,
		&i.SharedFinanceID,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + $2
WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID           `json:"id"`
	Balance decimal.NullDecimal `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}
