-- -- name: CreateUserAlert :one
-- INSERT INTO user_alerts (
--   user_id,
--   shared_finance_id,
--   name,
--   trigger_type,
--   threshold_amount,
--   category_id,
--   account_id,
--   comparison_operator,
--   frequency,
--   is_active,
--   created_at,
--   updated_at
--   ) VALUES (
--   $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
--   ) RETURNING id, created_at, updated_at;
